Abington_Map = {
    'Woodland Building': ['A','K','L','AF','J'],
    'Lares Building': ['H', 'G', 'P', 'Q'],
    'Sutherland Building': ['U', 'S', 'R', 'Lion Shrine', 'Sutherland Auditorium'],
    'Sutherland Auditorium': ['V', 'Sutherland Building'],
    'Athletic Building': ['AH', 'AI', 'AK', 'AJ'],
    'Rydal Building': ['AD', 'AG', 'AF'],
    'Springhouse': ['J', 'I'],
    'Lion Shrine': ['P', 'S', 'Sutherland Building'],
    'Tennis Court': ['AH', 'AL'],
    'Cloverly Building': ['AJ'],
    'A': ['Woodland Building', 'J', 'L', 'B'],
    'B': ['A', 'C', 'D'],
    'C': ['B', 'D', 'F'],
    'D': ['B', 'C', 'M', 'E'],
    'E': ['D', 'F', 'N'],
    'F': ['G', 'C', 'O', 'E'],
    'G': ['F', 'I', 'Lares Building'],
    'H': ['Lares Building', 'I'],
    'I': ['H', 'Springhouse', 'J'],
    'J': ['Springhouse', 'I', 'Woodland Building', 'A'],
    'K': ['Woodland Building', 'L', 'AF'],
    'L': ['K', 'Woodland Building', 'A'],
    'M': ['D', 'AE'],
    'N': ['E', 'T', 'P', 'Y'],
    'O': ['Lares Building', 'P', 'F'],
    'P': ['Q', 'O', 'N', 'Lion Shrine'],
    'Q': ['Lares Building', 'P'],
    'R': ['Sutherland Building'],
    'S': ['Sutherland Building', 'T', 'U', 'Lion Shrine'],
    'T': ['U', 'N', 'U'],
    'U': ['Sutherland Building', 'T', 'V', 'S'],
    'V': ['U', 'W', 'Sutherland Auditorium'],
    'W': ['V', 'X'],
    'X': ['Y', 'W', 'AN', 'AM'],
    'Y': ['N', 'Z', 'X'],
    'Z': ['AA', 'Y'],
    'AA': ['AB', 'Y'],
    'AB': ['AA', 'AC', 'AH'],
    'AC': ['AG', 'AB', 'AE'],
    'AD': ['Rydal Building', 'AG', 'AF'],
    'AE': ['AC', 'AF', 'M'],
    'AF': ['Rydal Building', 'Woodland Building', 'AE', 'AD', 'K'],
    'AG': ['AC', 'Rydal Building', 'AD', 'AJ'],
    'AH': ['Tennis Court', 'Athletic Building', 'AI', 'AB'],
    'AI': ['Athletic Building', 'AK', 'AH', 'AL'],
    'AJ': ['Cloverly Building', 'Athletic Building', 'AG'],
    'AK': ['Athletic Building', 'AI', 'AL'],
    'AL': ['AM', 'Tennis Court', 'AI', 'AK'],
    'AM': ['AL', 'X'],
    'AN': ['X']
}